### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bmuessig** [ZakKemble/millis#1]
Hello!

While this Library is really awesome, it hurts seeing it released under GPL. Couldn't you release it under a more permissive License such as MIT or BSD which are way more usable and still give you credit?

**Comment by DerAndere1** [comment]
I would strongly recommend the same as @bmuessig . The Arduino library handles this smarter, as it is at least licensed under LGPL 2.1. Viral licenses like GPL are not recommended for libraries. Even the GPL authors recommend something like LGPL instead of GPL for libraries. Consider MIT or BSD or the Apache 2.0 license as an alternative.  Thx for your consideration.

**Comment by GitMoDu** [comment]
Seconded, MIT ftw.

**Comment by ZakKemble** [comment]
Alright, I'll see about changing the license then.

**Comment by DerAndere1** [comment]
Just for your info (no guarantee, im not your lawyer):  Lets assume you now would choose LGPL 2.1 (e.g. in case this would be derived work from the Arduino core library). I guess you can then do one of the following: 
a) remove all old License information and replace it with "LGPL 2.1" or 
b) you can duplicate this repo and license it under LGPL 2.1+, or
c) change the license of this repo to say it is dual licensed under  GPL-3.0 **or** LGPL 2.1+

In either case, **in effect** I think your work will be then dual-licensed under the terms of GPL-3.0 **OR** LGPL 2.1+ (meaning the user can choose which of the two he wants to apply). This fact does not hurt anyone and you dont have to mention it explicitly. Just do not write "this work is licensed under the terms of GPL-3.0 AND LGPL 2.1+" anywhere (meaning the user has to comly to both licenses at the same time which would be a regression). Just my 5 cents

**Comment by ZakKemble** [comment]
Now dual licensed under GPL-3.0 or MIT :)

**Comment by DerAndere1** [comment]
Thx, makes things easier. I like your work. I didn't notice until recently that you also provide an actually working [AVR toolchain 7.3.0](http://blog.zakkemble.net/avr-gcc-builds/) . AVR-C99/C++14 classes here we come :)
